
[phases.setup]
nixPkgs = ["python312"]

[phases.install]
cmds = ["python -m pip install --upgrade pip", "python -m pip install -r requirements.txt"]

[start]
#nixpacks.toml
[phases.setup]


[phases.install]

#Command to install dependencies from requirements.txt
#Using "python -m pip" is more robust in some environments
cmds = ["python -m pip install --upgrade pip", "python -m pip install -r requirements.txt"]

[start]

#Command to start the application with Gunicorn
#It binds to all interfaces and uses the port provided by the PORT environment variable.
